--멤버
    drop table INSTA_MEMBER
   cascade constraint;
   
   drop sequence SEQ_INSTA_MEMBER
   
CREATE TABLE INSTA_MEMBER(
		SEQ NUMBER(8) PRIMARY KEY,
		ID VARCHAR2(50) NOT NULL,
		PWD VARCHAR2(50) NOT NULL,
		EMAIL VARCHAR2(50) NOT NULL,
		NAME VARCHAR2(50) NOT NULL,
		REGI_DATE DATE NOT NULL,
		INTRO VARCHAR2(1000),
		PROFILE_IMAGE VARCHAR2(500),
		HOMEPAGE VARCHAR2(500)
	);

	CREATE SEQUENCE SEQ_INSTA_MEMBER;
	
	select * from INSTA_MEMBER

   
   
   --팔로우 관련
   
CREATE TABLE INSTA_FOLLOW(
	SEQ NUMBER(8) PRIMARY KEY,
	MEMBER_SEQ NUMBER(8) NOT NULL,
	FOLLOW NUMBER(8) NOT NULL,	
	FOLLOW_CONNECT NUMBER(8) NOT NULL 
	);
	
CREATE SEQUENCE SEQ_INSTA_FOLLOW;

ALTER TABLE INSTA_FOLLOW
ADD CONSTRAINT FK_INSTA_FOLLOW_MEMBER_SEQ FOREIGN KEY(MEMBER_SEQ)
REFERENCES INSTA_MEMBER(SEQ);

ALTER TABLE INSTA_FOLLOW
ADD CONSTRAINT FK_INSTA_FOLLOW_FOLLOW FOREIGN KEY(FOLLOW)
REFERENCES INSTA_MEMBER(SEQ);	
 
DROP TABLE INSTA_FOLLOW
CASCADE CONSTRAINT;

DROP SEQUENCE SEQ_INSTA_FOLLOW;

select * from INSTA_FOLLOW
insert into INSTA_FOLLOW(SEQ, MEMBER_SEQ, FOLLOW, FOLLOW_CONNECT) values (SEQ_INSTA_FOLLOW.nextval, 1, 22, 0)
update INSTA_FOLLOW set FOLLOW_CONNECT=1 where MEMBER_SEQ=1 AND FOLLOW=21
delete from INSTA_FOLLOW where seq=11

--피드
DROP TABLE INSTA_PEED
CASCADE CONSTRAINT

DROP SEQUENCE SEQ_INSTA_PEED

CREATE TABLE INSTA_PEED(
	SEQ NUMBER(8) PRIMARY KEY,
	MEMBER_SEQ NUMBER(8) NOT NULL,
	MEMBER_ID VARCHAR2(50) NOT NULL,
	MEMBER_PROFILE_IMAGE VARCHAR2(500),
	IMAGE VARCHAR2(500) NOT NULL,
	PEED_LIKE NUMBER(38) NOT NULL,
	REGI_DATE DATE NOT NULL,
	CONTENT VARCHAR2(4000)
)

ALTER TABLE INSTA_PEED
ADD CONSTRAINT FK_INSTA_PEED_MEMBER_SEQ FOREIGN KEY(MEMBER_SEQ)
REFERENCES INSTA_MEMBER(SEQ);

CREATE SEQUENCE SEQ_INSTA_PEED;

select * from INSTA_PEED

--피드 댓글
DROP TABLE INSTA_PEED_REPLY
CASCADE CONSTRAINT;

DROP SEQUENCE SEQ_INSTA_PEED_REPLY;

	CREATE TABLE INSTA_PEED_REPLY(
		SEQ NUMBER(8) PRIMARY KEY,
		PEED_SEQ NUMBER(8) NOT NULL,
		MEMBER_SEQ NUMBER(8) NOT NULL,
		CONTENT VARCHAR2(4000),
		REGI_DATE DATE NOT NULL
	)
	
	ALTER TABLE INSTA_PEED_REPLY
	ADD CONSTRAINT FK_INSTA_PEED_REPLY_PEED_SEQ FOREIGN KEY(PEED_SEQ)
	REFERENCES INSTA_PEED(SEQ);

	ALTER TABLE INSTA_PEED_REPLY
	ADD CONSTRAINT FK_INSTA_PEED_REPLY_MEMBER_SEQ FOREIGN KEY(MEMBER_SEQ)
	REFERENCES INSTA_MEMBER(SEQ);

	CREATE SEQUENCE SEQ_INSTA_PEED_REPLY;


	--좋아요
	  	CREATE TABLE INSTA_THUMBSUP(
	SEQ NUMBER(8) PRIMARY KEY,
	MEMBER_SEQ NUMBER(8) NOT NULL,
	PEED_SEQ NUMBER(8) NOT NULL,
	LIKE_STATE NUMBER(3) NOT NULL,
	REGI_DATE DATE NOT NULL
);

CREATE SEQUENCE SEQ_INSTA_THUMBSUP;

ALTER TABLE INSTA_THUMBSUP
ADD CONSTRAINT FK_INSTA_THUMBSUP_MEMBER_SEQ FOREIGN KEY(MEMBER_SEQ)
REFERENCES INSTA_MEMBER(SEQ);

ALTER TABLE INSTA_THUMBSUP
ADD CONSTRAINT FK_INSTA_THUMBSUP_PEED_SEQ FOREIGN KEY(PEED_SEQ)
REFERENCES INSTA_PEED(SEQ);

DROP TABLE INSTA_THUMBSUP CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_INSTA_THUMBSUP;

--알림
DROP TABLE INSTA_NOTICE
CASCADE CONSTRAINT

DROP SEQUENCE SEQ_INSTA_NOTICE
 
 CREATE TABLE INSTA_NOTICE(
      SEQ NUMBER(8) PRIMARY KEY,
      MEMBER_SEQ NUMBER(8) NOT NULL,
      WHO_SEQ NUMBER(8) NOT NULL,
      WHO_ID VARCHAR2(500) NOT NULL,
      WHO_PROFILE VARCHAR2(500),
      WHAT NUMBER(8) NOT NULL,
      FEED_SEQ NUMBER(8),
      REGI_DATE DATE NOT NULL,
      READ_CONFIRM NUMBER(8) NOT NULL
  )
  
CREATE SEQUENCE SEQ_INSTA_NOTICE;
  
ALTER TABLE INSTA_NOTICE
ADD CONSTRAINT FK_INSTA_NOTICE_MEMBER_SEQ FOREIGN KEY(MEMBER_SEQ)
REFERENCES INSTA_MEMBER(SEQ);  
 
ALTER TABLE INSTA_NOTICE
ADD CONSTRAINT FK_INSTA_NOTICE_WHO_SEQ FOREIGN KEY(WHO_SEQ)
REFERENCES INSTA_MEMBER(SEQ);  

select * from INSTA_NOTICE

select to_char(REGI_DATE, 'yyyymmddhhmmss') AS REGI_DATE  from INSTA_NOTICE

insert into INSTA_NOTICE values(SEQ_INSTA_NOTICE.nextval, 1, 2, '11', 0, 1, sysdate, 0);
insert into INSTA_NOTICE values(SEQ_INSTA_NOTICE.nextval, 1, 2, '11', 1, 1, sysdate, 0);
insert into INSTA_NOTICE values(SEQ_INSTA_NOTICE.nextval, 1, 2, '11', 2, NULL, sysdate, 0);

