
CREATE TABLE INSTAMEMBER(
		SEQ NUMBER(8) PRIMARY KEY,
		ID VARCHAR2(50) NOT NULL,
		PWD VARCHAR2(50) NOT NULL,
		EMAIL VARCHAR2(50) NOT NULL,
		NAME VARCHAR2(50) NOT NULL,
		REGI_DATE DATE NOT NULL,
		OPEN NUMBER(2),
		PROFILE_IMAGE VARCHAR2(500)
	);

	CREATE SEQUENCE SEQ_INSTA_MEMBER;
	
	select * from INSTAMEMBER
	
   drop table INSTAMEMBER
   cascade constraint;
   
   drop sequence SEQ_INSTA_MEMBER